### ISSUE TITLE
Throughput decreases when receiving a large number of messages

### ISSUE THREAD

**Issue by RobinsonWM** [cosullivan/SmtpServer#63]
When receiving a large number of messages over a short period of time (e.g. 250,000 messages over a period of 2 minutes,) I am seeing very high CPU usage (95%+) and memory usage (3 GB+.)  The server initially accepts messages quickly but then slows down to the point of accepting only one message every few seconds.
Profiling showed contention related to `TaskExtensions.WithTimeout()`'s usage of `Task.Delay()`.
I'm using .NET Core 2.0 on Windows 10 x64.  My application is doing almost nothing - just calling `Interlocked.Increment()` to track the amount of messages it receives, so I don't suspect any code in my application.

**Comment by RobinsonWM** [comment]
As a workaround, I tried a different implementation of `TaskExtensions.WithTimeout()`, and the server was able to sustain 2,000 messages per second for several minutes using ~60% CPU and <20 MB.

```csharp
        public static async Task<T> WithTimeout<T>(this Task<T> task, TimeSpan timeout, CancellationToken cancellationToken)
        {
            var result = new TaskCompletionSource<T>();
            using (new Timer(_ => result.TrySetException(new TimeoutException()), null, timeout, Timeout.InfiniteTimeSpan))
            {
                //if you uncomment this line, the problem seems to come back:
                //cancellationToken.Register(() => timer.Dispose());

                task.ContinueWith(_ =>
                {
                    if (task.IsCanceled)
                    {
                        result.TrySetCanceled();
                    }
                    else if (task.IsFaulted)
                    {
                        result.TrySetException(task.Exception);
                    }
                    else
                    {
                        result.TrySetResult(task.Result);
                    }
                });

                return await result.Task;
            }
        }
```

**Comment by cosullivan** [comment]
Hi,

The high CPU and memory usage are probably not much of an issue, the machine will always use as much CPU as it needs to (especially if nothing else is running).

In regards to the slow down you are experiencing, I would suspect this is probably due to port exhaustion in Windows rather than anything related to the SMTP server itself. 

By default, Windows is not configured to handle a large volume of TCP connections but it is easily changed. The two settings you need to tweak in the registry are TcpTimedWaitDelay and MaxUserPort.

If the values don't exist in the registry you can create them here (both are REG_DWORD);
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\ Services\TCPIP\Parameters

My suggestions would be to set TcpTimedWaitDelay to 30 and MaxUserPort to 32768.

Have a look at this for reference;
https://docs.oracle.com/cd/E23095_01/Search.93/ATGSearchAdmin/html/s1207adjustingtcpsettingsforheavyload01.html

Let me know if these changes make a difference.

Thanks,
Cain.

**Comment by RobinsonWM** [comment]
Thanks for the suggestions, and sorry for my slow response.  I tried making those changes and restarting the computer, and they didn't seem to make a difference.
To give some background on my use case, I'm trying to use this library to simulate an MTA in order to test throughput of an application that sends mail.  The application I'm testing opens up only a few (fewer than 20) long-lived SMTP connections and sends many messages over each one.

In my test, I was sending 250,000 messages as fast as my application could send them.
Using the registry changes you suggested, without the hack I posted above, I saw an average throughput of 56 messages per second, but the throughput seemed to decrease the longer I ran the test.
Using an `SmtpServer.dll` built with the hack I posted above, I saw average throughput of 1,766 messages per second.  The memory usage was much lower in this case.
In both cases, the CPU usage was near 100%, which is good.

Here is the Visual Studio 2017 profiling I was looking at that showed `TaskExtensions.WithTimeout()`'s usage of `Task.Delay()` in the hot path for contention, which is what led me to try the hack I posted above:
[dotnet180426.zip](https://github.com/cosullivan/SmtpServer/files/1969128/dotnet180426.zip)

**Comment by cosullivan** [comment]
Hi, 

Thanks for your feedback and time on this, I will have a look into this.

I spent a fair bit of time on performance testing & tuning using the Enron Corpus (https://en.wikipedia.org/wiki/Enron_Corpus) a while back, but I've also made some fairly big internal changes since then too.

Thanks,
Cain.

**Comment by RobinsonWM** [comment]
The 5.1.0 package is working great for me!  In a quick test, I saw throughput of 1,573 messages/second.  Thanks!

**Comment by reinaldocoelho** [comment]
Hi, this thread still open or need to be closed?

**Comment by reinaldocoelho** [comment]
No problem :-D

Thanks.

**Comment by siewers** [comment]
Is this still an issue?

**Comment by cosullivan** [comment]
> Is this still an issue?

No, this is resolved.
