### ISSUE TITLE
Forwarding

### ISSUE THREAD

**Issue by thyn** [cosullivan/SmtpServer#89]
Is it possible to forward email to another email server? I need intermediate server for message validation with forwarding to another email server.

**Comment by cosullivan** [comment]
Hi,

Yes it is, but not purely with this. 

The SmtpServer package will allow you to receive the message but you will need to implement a custom IMessageStore which then forwards it on.

Thanks,
Cain.

**Comment by schommi** [comment]
Hey, 

in a very similar manner I want to forward emails, however I would like to have the server work as a relay. To make this happen
* I would require authentication, when sending from an account on this server to somewhere else (to prevent having an open relay), however
* sending mails to accounts on this server should be possible without authentication.

I tried to return a corresponding error in the **SaveAsync** method of the **MessageStore**, however my mail client (I used Thunderbird to test) does not see the return code as a reason to display a prompt for credentials hence signals, that the mail delivery just failed.
I noticed, that the **SmtpResponse** class offers an AuthenticationRequired result code (530), however i found some posts, that the code 550 should be used (e.g. https://portal.smartertools.com/kb/a2628/550-authentication-is-required-for-relay-when-sending-email.aspx). I tried to give back a 550 result by typecasting the int to the enumeration, but was unsuccessful as well.

Do you have any idea, what I'm doing wrong here?

Cheers,
Andreas

**Comment by cosullivan** [comment]
Hi,

I am not sure how Thunderbird works but I doubt it would prompt for credentials once it receives an error (either a 530 or a 550). 

The reason for this is that the authentication needs to be advertised by the Server to the client when the client first connects and performs the initialization sequence (either the HELO or EHLO). The AUTH PLAIN LOGIN command will be advertised back to the client as long as certain conditions are met;
a) you need to have configured an instance of a UserAuthenticatorFactory, and 
b) the channel needs to be secure such that the client has called the STARTTLS command or you have configure the Endpoint to allow for unsecure authentication using AllowUnsecureAuthentication(true) on the Endpoint definition.

I would suggest that it is one of two problems;
a) Thunderbird is not smart enough to prompt for credentials when it receives these errors, but I may be wrong. If it is it would need to reset the mail transaction and start again. Usually the mail clients just display these error messages and then its up to the users to determine how they need to be resolved, ie, you would then need to add your credentials into Thunderbird.
b) Assuming Thunderbird is smart enough, if you haven't configured the server correctly it might not be advertising the AUTH PLAIN LOGIN command and thus Thunderbird is assuming (and rightfully so) that the server doesn't support authentication. 
c) Also ensure that if you want to use authentication that Thunderbird is making a secure connection or that you configure the endpoint to allow authentication without a secure connection.

If you have a look at this sample;
https://github.com/cosullivan/SmtpServer/blob/master/Src/SampleApp/Examples/SessionTracingExample.cs
it shows you how to enable tracing and that way you can see what commands are actually being called by the mail client.

If you can shared any code (specifically the configuration of the SmtpServerOptionsBuilder) than that will help.

Thanks,
Cain.

**Comment by schommi** [comment]
Cain, 

first of all thanks for your swift reply. I really appreciate you taking the time. I Added tracing as suggested in the link. My server configuration looks like this:

ISmtpServerOptions options = new SmtpServerOptionsBuilder()
	.ServerName("localhost")
	.MessageStore(container.GetInstance<IMessageStoreFactory>())
	.MailboxFilter(container.GetInstance<IMailboxFilterFactory>())
	.UserAuthenticator(container.GetInstance<IUserAuthenticatorFactory>())
	.Endpoint(new EndpointDefinitionBuilder().AllowUnsecureAuthentication(true).AuthenticationRequired(true).Port(25).IsSecure(false).Build())
	.Build();

At this point I'm trying to get the server going on my development machine without SSL. I specified the port before just with the .Port method, this however resulted in my authenticator not being invoked at all.
Specfying the endpoint like this makes the server request credentials. This is the log ouput before I enter the password:

SessionCreated: 127.0.0.1:49487
EHLO: DomainOrAddress=127.0.0.1
AUTH: Method=Plain, Parameter=AHNjaG9tbWkAcGFzcw==

Changing AuthenticationRequired to false does not change this. My mail client prompts for credentials right away. Authentication happens before I have a chance to return an error, my initial try was to return the error in the MessageStore, depending on whether the mail should be relayed or not. The MessageStore is called after I authenticated successfully, so I am forced to authenticate not matter what. 

I just returned AuthenticationRequired to check this inside the message store:

return SmtpResponse.AuthenticationRequired;

If I understand relaying correctly, I would expect, that the decision to require credentials comes at the point, where a mail is actually handed over to the server. Let's say another user used his own server, which relays messages to my server. In that case the other mail server would not need to authenticate. However if I would use my mail server to relay to the other user's mail server, I would have to authenticate. If I could relay like that anonymously, the mail server would be an open relay and would probably join forces with some spamming network :)
I'm not sure, how this is actually supposed to work, whether the session is reset in case authentication is required (like you suggested in a) or if a client intending to relay indicates this right away when logging in.
I'm aware, that this is in no way a bug in your library or something - you did not intend to support relaying in the first place. I was just hoping, that you had an idea on how to get out of it.

If you have no idea right away on what else I could try, I will try sniffing traffic with my ISPs SMTP server which does support relaying and try to find out what's different. I will keep you informed if I find out anything interesting.

Again, thanks alot for your help oin this.

Cheers,
Andreas

**Comment by cosullivan** [comment]
Hi Andreas,

Another place you could try returning the error is within a custom implementation of IMailboxFilter. Have a look here for an example of how that works;
https://github.com/cosullivan/SmtpServer/blob/master/Src/SampleApp/SampleMailboxFilter.cs

The IMailboxFilter happens prior to the message being exchanged which may work for Thunderbird. You would be looking to implement the logic in the CanDeliverToAsync method.

Thanks,
Cain.

**Comment by schommi** [comment]
Cain,

thanks for the link, this one helped me figure out, what happens, I additionally found some web resources. I logged an SMTP conversation between Thunderbird and my ISPs mail server to see, what happens, when not relaying. I added comments starting with a #.

220 mail.aschommer.de ESMTP
EHLO [192.168.0.11]
250-mail.aschommer.de
250-SIZE 20480000
250 AUTH LOGIN
AUTH LOGIN
334 VXNlcm5hbWU6 # "Username:"

----- # Thunderbird prompts for the password

dGVzdG1haWxAaG9tZS5jb20= # "testmail@home.com"
334 UGFzc3dvcmQ6 # "Password:"
bXlwYXNzd29yZA== # "mypassword"
235 authenticated.
MAIL FROM:<mail@somewhere.com> SIZE=420
250 OK
RCPT TO:<mail@home.com>
250 OK
DATA
354 OK, send.
#... mail goes here

So as far as a get it, Thunderbird indicated right away, that it wanted to authenticate.

Then I logged two conversations trying to relay. One is an allowed relay (target account is on my server), the second is forbidden, since the target is somewhere else. I used telnet to create these two conversations.

220 mail.home.com ESMTP
EHLO me@somehwere.com
250-mail.home.com
250-SIZE 20480000
250 AUTH LOGIN
MAIL FROM: me@somewhere.com
250 OK
RCPT TO: me@home.com
250 OK

Now the conversation with a denied relay:

220 mail.home.com ESMTP
HELO me@somewhere.com
250 Hello.
MAIL FROM: me@somewhere.com
250 OK
RCPT TO: me@somewhereelse.com
530 SMTP authentication is required.**

I found some articles on the web, how the SMTP conversation should go. This article: https://wiki.hetzner.de/index.php/Mailserver_Relaytest (unfortunately in german language) says, that the server responds with 554 <xx@xyz.xx>: Relay access denied (instead of 530), so the exact error does not appear to be that important.

As far as I understand, the IMailboxFilter hook should work, i noticed, that the result errors are being translated to code 550 (with different text messages). Is there a chance that you allow returning 530/554 as stated in the article I linked and the SMTP conversation I logged with my ISPs mail server? I could imagine, that relaying servers may react differently, when my server responds that I mailbox is unavailable, though the actual problem is that relaying is denied. 

Again, thanks for all your help and your great SMTP library.

Cheers,
Andreas

**Comment by cosullivan** [comment]
Hi Andreas,

Your analysis here is great. One thing I noticed that might be a difference is that your ISP's mail server uses AUTH LOGIN whereas I am using AUTH PLAIN LOGIN. From memory (it was a while ago that I did that part) they are two different things so perhaps that could be part of the issue. I will refresh my knowledge on that.

With regards the error code mapping in the IMailboxFilter, I will look at adding some new enum's here but for now if you want to test this you can throw an SmtpResponseException with your desired response code and that response code will be sent instead.

Thanks,
Cain.
