### ISSUE TITLE
Crash due to no available sockets

### ISSUE THREAD

**Issue by kbilsted** [cosullivan/SmtpServer#90]
Hi Sullivan

Great library! I was quick to throw together a working example. However Im facing many many open sockets (more than 1000)

	  TCP    127.0.0.1:57378        dev:smtp               TIME_WAIT
	  TCP    127.0.0.1:57379        dev:smtp               TIME_WAIT
	  TCP    127.0.0.1:57380        dev:smtp               TIME_WAIT
	  TCP    127.0.0.1:57381        dev:smtp               TIME_WAIT
	  TCP    127.0.0.1:57382        dev:smtp               TIME_WAIT
	  TCP    127.0.0.1:57383        dev:smtp               TIME_WAIT
	  TCP    127.0.0.1:57384        dev:smtp               TIME_WAIT
	  TCP    127.0.0.1:57385        dev:smtp               TIME_WAIT
	  TCP    127.0.0.1:57386        dev:smtp               TIME_WAIT
	  TCP    127.0.0.1:57387        dev:smtp               TIME_WAIT

We see that after around receiving 16000 mails it crashes as there are no more sockets free on my machine

I've pushed code for you to test on your machine on https://github.com/kbilsted/SmtpServerDemo just run the two projects and observe ;)

**Comment by cosullivan** [comment]
Hi @kbilsted ,

Apologies for not responding to this but I am not getting my GitHub notifications come through on email anymore for some reason.

Did you find a resolution to your issue that you were facing? If you are running this on Windows it sounds like it could be due to port exhaustion (that TIME_WAIT state is perfectly normal for TCP/IP). Windows (by default) is not configure to handle a large amount of throughput on TCP/IP connections but you can change that;
https://docs.oracle.com/cd/E23095_01/Search.93/ATGSearchAdmin/html/s1207adjustingtcpsettingsforheavyload01.html

Thanks,
Cain.

**Comment by kbilsted** [comment]
Hi @cosullivan 

thanks for reaching out. I found the problem to be in the use of the `SmtpClient` (not your framework). It was using a new connection each time due to setting the connection details in my inner loop.
